services:
  social-gateway:
    container_name: social-gateway
    image: wangtao/social-gateway:1.0
    ports:
      - 9080:9080
    environment:
      TZ: Asia/Shanghai
      NACOS_HOST: host.docker.internal
      NACOS_PORT: 8848
      NACOS_NAMESPACE: 1dab4474-cbfe-4d1d-ad46-d41c8683bf51
    command: ["java", "-Dreactor.netty.http.server.accessLogEnabled=true", "-jar", "app.jar"]
    networks:
      social-app:
        aliases:
          - social-gateway

  social-user:
    container_name: social-user
    image: wangtao/social-user:1.0
    ports:
      - 9081:9081
    environment:
      TZ: Asia/Shanghai
      NACOS_HOST: host.docker.internal
      NACOS_PORT: 8848
      NACOS_NAMESPACE: 1dab4474-cbfe-4d1d-ad46-d41c8683bf51
    command: ["java", "-jar", "app.jar"]
    networks:
      social-app:
        aliases:
          - social-user

  social-square:
    container_name: social-square
    image: wangtao/social-square:1.0
    ports:
      - 9082:9082
    environment:
      TZ: Asia/Shanghai
      NACOS_HOST: host.docker.internal
      NACOS_PORT: 8848
      NACOS_NAMESPACE: 1dab4474-cbfe-4d1d-ad46-d41c8683bf51
    command: ["java", "-jar", "app.jar"]
    networks:
      social-app:
        aliases:
          - social-square

  social-file-storage:
    container_name: social-file-storage
    image: wangtao/social-file-storage:1.0
    ports:
      - 9083:9083
    environment:
      TZ: Asia/Shanghai
      NACOS_HOST: host.docker.internal
      NACOS_PORT: 8848
      NACOS_NAMESPACE: 1dab4474-cbfe-4d1d-ad46-d41c8683bf51
    command: [ "java", "-jar", "app.jar" ]
    networks:
      social-app:
        aliases:
          - social-file-storage

networks:
  social-app:
    name: social-app
    driver: bridge