db:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456

redis:
  nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
  password: 123456

minio:
  # 必须要加上http
  endpoint: "http://127.0.0.1:9000"
  access-key: LhulnOUakqQPuuPf6u3R
  secret-key: adSFdJU6qojXTQXzYjNYG5BdoLsZ2DBpf7mEjpgi
  default-bucket: social-app
  # 客户端访问图片的地址, 使用域名代替, 使用本地地址的话别的机器访问不了
  img-access-addr: "http://img.social.wangtao.com:9000"

rocketmq:
  host: 127.0.0.1
  port: 9876

es:
  host: 127.0.0.1
  port: 9200