db:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456

redis:
  nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
  password: 123456

minio:
  # 必须要加上http
  endpoint: "http://img.social.wangtao.com:9000"
  access-key: LhulnOUakqQPuuPf6u3R
  secret-key: adSFdJU6qojXTQXzYjNYG5BdoLsZ2DBpf7mEjpgi
  default-bucket: social-app

rocketmq:
  host: 127.0.0.1
  port: 9876

es:
  host: 127.0.0.1
  port: 9200