spring:
  servlet:
    multipart:
      # 单次请求允许传输字节的最大值
      max-request-size: 100MB
      # 设置单个文件最大长度
      max-file-size: 20MB
      # 当文件达到多少时写入到临时目录, 而不是保留在内存中
      file-size-threshold: 20MB
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/socialdb?useUnicode=true&characterEncoding=utf-8&&serverTimezone=Asia/Shanghai
    username: ${db.username}
    password: ${db.password}
    druid:
      # 初始化时建立连接的个数
      initial-size: 5
      # 最大连接数量
      max-active: 20
      # 最小连接数量
      min-idle: 5
      # 获取连接等待的超时时间(毫秒)
      max-wait: 60000
      # 获取连接时要不要对该连接进行有效性校验
      test-on-borrow: false
      # 归还连接时要不要对该连接进行有效性校验
      test-on-return: false
      # 是否需要检查空闲的连接有效性
      test-while-idle: true
      # 用来检测连接是否有效的sql
      validation-query: select 1
      # 配置间隔多久才进行一次检测, 检测需要关闭的空闲连接，单位是毫秒
      # 也是test-while-idle的依据, 如果申请的连接空闲时间大于该参数, 需要检测连接是否有效
      time-between-eviction-runs-millis: 3000
      # 一个连接在池中最小生存的时间, 单位是毫秒
      min-evictable-idle-time-millis: 600000
      # 个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 慢查询
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-log-level: WARN
          slow-sql-millis: 1000

mybatis-plus:
  global-config:
    db-config:
      logicDeleteField: delFlg
      logic-delete-value: 1
      logic-not-delete-value: 0