spring:
  redis:
    cluster:
      nodes: ${redis.nodes}
    password: ${redis.password}
    connect-timeout: 5000
    timeout: 30000
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: 60000
        min-idle: 5